version: "3"
services:
  api:
    image: inventory-api:latest
    container_name: inventory_api
    command: --spring.config.location=file:/config/application.yml  # external application.yml
    restart: always
    volumes:
      - ./config:/config  # map application.yml directory to container
    expose:
      - 8081  # same as server.port in config/application.yml
    networks:
      - internal
      - mysql_conn

  client:
    build:
      image: inventory-client:latest
      context: ./inventory-client
      args:
        EXPOSE_PORT: 4123
    container_name: inventory_client
    restart: always
    depends_on:
      - api
    expose:
      - 4123
    environment:
      # node environment variables
      NODE_ENV: production
      PORT: 4123
      API_URL: http://api:8081
      PANEL_USER: demo
      PANEL_PASS: demo

      # used for nginx-proxy
      # uncomment if you are using Nginx Proxy 
      #VIRTUAL_HOST: your.domain.tld
      #VIRTUAL_PORT: 4123
      #LETSENCRYPT_HOST: your.domain.tld
      #LETSENCRYPT_EMAIL: email@example.com
    
    # Used only when NOT using nginx-proxy
    ports:
      - "8080:4123"   # expose frontend at port 9000

    networks: 
      - internal
     # - proxy  # uncomment for Nginx Proxy
networks:
  internal:   # connection between api and ExpressJS reverse proxy (inventory-client/server/server.js)
  mysql_conn:
    external:
      name: database-net  # to connect with external MySQL database
  #proxy:    # uncomment if you are using Nginx-Proxy
  #  external:
  #    name: nginx-proxy   # your proxy network name